### ISSUE TITLE
初回ロード時の速度を早くしたい

### ISSUE THREAD

**Issue by kangaechu** [kotei-senpin/roadmap#6]

**Comment by yktakaha4** [comment]
特にトップページは影響が大きいので、検索結果をssgしたものをs3に置いておくと早くなるのか検討したいとは思っています...でも購入の度に在庫等を反映したものを置き直す必要がある認識なので、ちょっと悩んでいます

裏側の話を言うと、バックエンドがlambdaでなにも考えないで作ると初回起動時4~5秒かかっちゃうのですが、
トップページの表示に必要な諸情報を返すバックエンドは、セッションに関するもの以外は現状cloudfrontでキャッシュしており、多少軽減する工夫はしています
上記の理由で、ssrはかえって性能を落とすんじゃないかと思って試してないのですがよくわかってません...

**Comment by yktakaha4** [comment]
対応前後を比較できておらずなのですが、初期表示時に呼び出している新着結果一覧についてcloudfrontでのキャッシュを想定していたのですがうまくできていなかったらしく、
対処したところ、特に目視状では結構改善したように見えると思いますので一旦クローズとしたいと思います
ありがとうございました

<img width="760" alt="スクリーンショット 2020-11-14 20 00 12" src="https://user-images.githubusercontent.com/20282867/99145661-097ba900-26b4-11eb-969c-e6082cc2e444.png">
