### ISSUE TITLE
Google連携でログインするとアイコンが表示されない

### ISSUE THREAD

**Issue by Polarbear08** [kotei-senpin/roadmap#8]
おま環の可能性が無きにしもあらずなので、一応手元でも確認してみていただければと思います。
![account](https://user-images.githubusercontent.com/41717274/97988208-f3eac180-1e1f-11eb-8cd6-dd0fa2b58a2e.png)

**Comment by yktakaha4** [comment]
ありがとうございます！

ユーザーの画像について、私のアカウントについては `https://lh3.googleusercontent.com/ ` から配信されており、
セキュリティ向上のために設定していたCSPヘッダでも同様のオリジンを指定していたのですが、
おそらくはこちらがユーザー毎に違うエンドポイントになる可能性があり、その影響で画像が表示されなかったのではないかと推測しています
したがって、差し当たりCSPでの指定を `https://*.googleusercontent.com` に変更してみました。こちらで改善すれば幸いです

<img width="740" alt="スクリーンショット 2020-11-14 20 06 38" src="https://user-images.githubusercontent.com/20282867/99145798-f7e6d100-26b4-11eb-8246-6ec596b20678.png">
